"""The Qt pipeline editor.

Row labels, the reorder rules and the policy marks all come from
`ryos.pipelinesteps`, shared with the Tk editor — this draws the list and
wires the buttons. The legend under the list is the same one the Tk editor
shows, because the marks it explains are generated by the same function.
"""

from __future__ import annotations

from typing import Callable

from PySide6.QtWidgets import (QComboBox, QDialog, QDialogButtonBox,
                               QHBoxLayout, QLabel, QListWidget, QPushButton,
                               QVBoxLayout)

from .. import pipelinesteps
from ..db import (FAIL_CONTINUE, FAIL_STOP, WHEN_ALWAYS, WHEN_ON_FAILURE, WHEN_ON_SUCCESS)

LEGEND = ("∥ = starts together with the step above   ·   "
          "! = keeps going if it fails   ·   ↻n = retries   ·   "
          "?ok / ?fail = only after success / failure   ·   "
          "→launch = released once started")

_ON_FAILURE = ((FAIL_STOP, "Stop the pipeline"), (FAIL_CONTINUE, "Keep going"))
_RUN_WHEN = ((WHEN_ALWAYS, "Always"), (WHEN_ON_SUCCESS, "Only after success"),
             (WHEN_ON_FAILURE, "Only after a failure"))


class PipelineEditorDialog(QDialog):
    """Reorder a pipeline's steps and set each step's policy."""

    def __init__(self, pipeline_id: int, name: str, steps, parent=None, *,
                 on_reorder: Callable[[list], None] | None = None,
                 on_policy: Callable[[int, dict], None] | None = None):
        super().__init__(parent)
        self.setWindowTitle(f"Pipeline — {name}")
        self.pipeline_id = pipeline_id
        self._steps = list(steps)
        self._on_reorder = on_reorder
        self._on_policy = on_policy

        col = QVBoxLayout(self)
        self.list = QListWidget()
        col.addWidget(self.list, 1)

        controls = QHBoxLayout()
        self.up_button = QPushButton("▲ Up")
        self.down_button = QPushButton("▼ Down")
        self.remove_button = QPushButton("✕ Remove")
        self.trigger_button = QPushButton("∥ With Prev")
        for b in (self.up_button, self.down_button, self.remove_button,
                  self.trigger_button):
            controls.addWidget(b)
        controls.addStretch(1)
        col.addLayout(controls)

        policy = QHBoxLayout()
        self.on_failure = QComboBox()
        self.on_failure.addItems([label for _v, label in _ON_FAILURE])
        self.run_when = QComboBox()
        self.run_when.addItems([label for _v, label in _RUN_WHEN])
        self.retries = QComboBox()
        self.retries.addItems([str(n) for n in range(6)])
        policy.addWidget(QLabel("On failure"))
        policy.addWidget(self.on_failure)
        policy.addWidget(QLabel("Run when"))
        policy.addWidget(self.run_when)
        policy.addWidget(QLabel("Retries"))
        policy.addWidget(self.retries)
        policy.addStretch(1)
        col.addLayout(policy)

        legend = QLabel(LEGEND)
        legend.setObjectName("cardPath")
        legend.setWordWrap(True)
        col.addWidget(legend)

        buttons = QDialogButtonBox(QDialogButtonBox.StandardButton.Close)
        buttons.rejected.connect(self.reject)
        buttons.accepted.connect(self.accept)
        col.addWidget(buttons)

        self.up_button.clicked.connect(lambda: self.move(-1))
        self.down_button.clicked.connect(lambda: self.move(+1))
        self.list.currentRowChanged.connect(self._on_selection)
        self.reload(self._steps)

    # -- the list ----------------------------------------------------------
    def reload(self, steps) -> None:
        """Refill the list from step rows, keeping the selection if it exists."""
        self._steps = list(steps)
        keep = self.list.currentRow()
        self.list.clear()
        self.list.addItems(pipelinesteps.step_labels(self._steps))
        if 0 <= keep < self.list.count():
            self.list.setCurrentRow(keep)
        self._on_selection(self.list.currentRow())

    def selected_index(self) -> int | None:
        row = self.list.currentRow()
        return row if row >= 0 else None

    def _on_selection(self, row: int) -> None:
        # Step 1 has nothing above it to run alongside, so the control is
        # meaningless there rather than merely unused.
        self.trigger_button.setEnabled(
            not pipelinesteps.first_step_cannot_run_with_previous(
                row if row >= 0 else None))
        has = row >= 0
        self.up_button.setEnabled(
            pipelinesteps.can_move(row if has else None, len(self._steps), -1))
        self.down_button.setEnabled(
            pipelinesteps.can_move(row if has else None, len(self._steps), +1))
        for combo in (self.on_failure, self.run_when, self.retries):
            combo.setEnabled(has)

    # -- reordering --------------------------------------------------------
    def move(self, delta: int) -> None:
        idx = self.selected_index()
        # can_move already rejects None; stated here too because this module
        # sits outside the mypy scope (it imports PySide6), so nothing else
        # would catch it going wrong.
        if idx is None or not pipelinesteps.can_move(idx, len(self._steps),
                                                     delta):
            return
        ids = pipelinesteps.reorder([s[0] for s in self._steps], idx, delta)
        if self._on_reorder is not None:
            self._on_reorder(ids)
        # Reflect the move locally so the list is right even when the caller
        # does not hand back fresh rows.
        order = {sid: i for i, sid in enumerate(ids)}
        self.reload(sorted(self._steps, key=lambda s: order[s[0]]))
        self.list.setCurrentRow(idx + delta)
